### ISSUE TITLE
Duplicated pylsy.py

### ISSUE THREAD

**Issue by gonvaled** [Leviathan1995/Pylsy#22]
https://github.com/Leviathan1995/Pylsy/blob/master/pylsy/tests/pylsy.py

**Comment by leviathan0992** [comment]
because i need use pylsy.py in tests ,do you have a better solution?

**Comment by bcho** [comment]
@Leviathan1995 You should `import pylsy` in the test.

**Comment by leviathan0992** [comment]
@bcho i try to do it.but the path not right

**Comment by bcho** [comment]
@Leviathan1995 Please have a look at #24
