### ISSUE TITLE
Change 'row' to 'col'?

### ISSUE THREAD

**Issue by DrNightmare** [Leviathan1995/Pylsy#3]
The 'attributes' of the PylsyTable are technically columns, not rows (e.g. 'name' is a column, 'age' is a column, and so on). The current nomenclature might lead to confusion in the future. Do you want to consider changing 'row' to 'col' in pylsy.py?

Also, a small note: AddData() currently fills a column (e.g. give a list of names to fill in the 'name' column, etc.), whereas generally, data entry is done row-wise.

**Comment by leviathan0992** [comment]
this is what i want to do

**Comment by leviathan0992** [comment]
how about now? thank u

**Comment by DrNightmare** [comment]
Yeah, nomenclature is fine :)
