### ISSUE TITLE
Line no 35 in pylsy.py fails when there are no values assigned to a column.

### ISSUE THREAD

**Issue by OldPanda** [Leviathan1995/Pylsy#5]
Line no 35 in pylsy.py fails when there are no values assigned to a column.

For instance, this example:

attributes=["name"]
table=PylsyTable(attributes)
name=["sun","lsy","luna","leviathan"]
table.AddData("name",name)
table.CreateTable()

works fine, whereas changing the attributes list to 
attributes=["name", "age"]

triggers the error:
TypeError: can only concatenate list (not "str") to list

In fact, the example provided in README.MD would fail in this case.

This is because values in 'age' still haven't been initialized. In this case, there should be some validation to check whether the dict is empty before trying to find the word with highest length.

**Comment by leviathan0992** [comment]
what?

**Comment by OldPanda** [comment]
You forwarded this email to me, and I think it should appear here:).

**Comment by OldPanda** [comment]
Seems works now. I'll close this.
